@PixelzOrderSystem_HostAddress = http://localhost:5089

GET {{PixelzOrderSystem_HostAddress}}/api/orders?name=Order%201
Accept: application/json

###

POST {{PixelzOrderSystem_HostAddress}}/api/orders/checkout
Content-Type: application/json

{
  "orderId": "3fad2a40-65ce-4d83-a023-b023122d7ca5",
  "paymentType": 1
}
###